[package]
name = "lut_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lut_builder"
crate-type = ["cdylib"]

[dependencies]
png = "0.17.13"
pyo3 = "0.21.1"
